char sample[] = {
  "\"KAIST is the first and top science and technology university in Korea.\n"
  " KAIST has been the gateway to advanced science and technology,\n"
  " innovation, and entrepreneurship, and our graduates have been key\n"
  " players behind Korea’ innovations. KAIST will continue to pursue\n"
  " advances in science and technology as well as the economic development\n"
  " of Korea and beyond.\" --KAIST"
};
